/**
 * Demo data for local preview when Supabase is not configured.
 * Uses real facility data from our directory.
 */
import type { Facility, State, City } from "@/lib/types/facility";

const now = new Date().toISOString();

const facilityDefaults = {
  email: null,
  hours: null,
  images: [],
  review_count: 0,
  google_place_id: null,
  google_rating: null,
  google_review_count: 0,
  verified_at: null,
  verification_status: "unverified" as const,
  website_live: null,
  data_source: "manual",
  google_cid: null,
  rating_distribution: null,
  review_summary: null,
  review_pros: null,
  review_cons: null,
  best_for_tags: null,
  standout_quote: null,
  owner_response_rate: null,
  meta_title: null,
  meta_description: null,
  status: "active" as const,
  created_at: now,
  updated_at: now,
};

export const DEMO_FACILITIES: Facility[] = [
  {
    ...facilityDefaults,
    id: "demo-1",
    slug: "padel-haus-williamsburg",
    name: "Padel Haus Williamsburg",
    address: "307 Kent Ave",
    city: "Brooklyn",
    city_slug: "brooklyn",
    state: "New York",
    state_slug: "new-york",
    state_abbr: "NY",
    zip_code: "11249",
    latitude: 40.7138,
    longitude: -73.9614,
    phone: "(917) 970-0036",
    website: "https://www.padel.haus/locations/williamsburg",
    total_courts: 7,
    indoor_court_count: 4,
    outdoor_court_count: 3,
    surface_type: "artificial turf",
    description: "NYC's first premium indoor padel club in Williamsburg, Brooklyn, featuring spa-like locker rooms, social lounges, and a pro shop.",
    indoor_courts: true,
    outdoor_courts: true,
    panoramic_glass: true,
    led_lighting: true,
    pro_shop: true,
    equipment_rental: true,
    coaching: true,
    tournaments: true,
    leagues: true,
    open_play: true,
    locker_rooms: true,
    parking: false,
    food_beverage: true,
    wheelchair_accessible: false,
    kids_programs: false,
    price_per_hour_cents: 5000,
    price_peak_cents: 8000,
    membership_available: true,
    avg_rating: 4.8,
    review_count: 42,
    is_featured: true,
  },
  {
    ...facilityDefaults,
    id: "demo-2",
    slug: "reserve-padel-sole-mia",
    name: "Reserve Padel SoLe Mia",
    address: "2251 NE 146th St",
    city: "North Miami",
    city_slug: "north-miami",
    state: "Florida",
    state_slug: "florida",
    state_abbr: "FL",
    zip_code: "33181",
    latitude: 25.9092,
    longitude: -80.1652,
    phone: "(786) 562-6189",
    website: "https://www.reservepadel.com/sole-mia",
    total_courts: 10,
    indoor_court_count: 4,
    outdoor_court_count: 6,
    surface_type: "artificial turf",
    description: "Reserve Padel's first permanent 100,000 sq ft club with ten professional courts, a wellness center, gym, and Pura Vida cafe at SoLe Mia.",
    indoor_courts: true,
    outdoor_courts: true,
    panoramic_glass: true,
    led_lighting: true,
    pro_shop: true,
    equipment_rental: true,
    coaching: true,
    tournaments: true,
    leagues: true,
    open_play: true,
    locker_rooms: true,
    parking: true,
    food_beverage: true,
    wheelchair_accessible: true,
    kids_programs: true,
    price_per_hour_cents: 6000,
    price_peak_cents: 9000,
    membership_available: true,
    avg_rating: 4.9,
    review_count: 56,
    is_featured: true,
  },
  {
    ...facilityDefaults,
    id: "demo-3",
    slug: "los-angeles-padel-club",
    name: "Los Angeles Padel Club",
    address: "3801 Lenawee Ave",
    city: "Los Angeles",
    city_slug: "los-angeles",
    state: "California",
    state_slug: "california",
    state_abbr: "CA",
    zip_code: "90232",
    latitude: 34.0158,
    longitude: -118.3884,
    phone: null,
    website: "https://www.thelapc.com",
    total_courts: 7,
    indoor_court_count: 0,
    outdoor_court_count: 7,
    surface_type: "artificial turf",
    description: "LA's largest padel club with seven outdoor courts, coworking space, wellness amenities, members' lounge, gym, and free parking.",
    indoor_courts: false,
    outdoor_courts: true,
    panoramic_glass: true,
    led_lighting: true,
    pro_shop: true,
    equipment_rental: true,
    coaching: true,
    tournaments: true,
    leagues: true,
    open_play: true,
    locker_rooms: true,
    parking: true,
    food_beverage: true,
    wheelchair_accessible: true,
    kids_programs: false,
    price_per_hour_cents: 5000,
    price_peak_cents: 8000,
    membership_available: true,
    avg_rating: 4.7,
    review_count: 35,
    is_featured: true,
  },
  {
    ...facilityDefaults,
    id: "demo-4",
    slug: "padel39-austin",
    name: "Padel39 Austin",
    address: "2510 Rutland Dr",
    city: "Austin",
    city_slug: "austin",
    state: "Texas",
    state_slug: "texas",
    state_abbr: "TX",
    zip_code: "78758",
    latitude: 30.373,
    longitude: -97.7076,
    phone: "(512) 220-6296",
    website: "https://www.padel39.com",
    total_courts: 6,
    indoor_court_count: 0,
    outdoor_court_count: 6,
    surface_type: "artificial turf",
    description: "Premium padel club near The Domain and Q2 Stadium with 6 courts, an 8,000 sq ft clubhouse, recovery area, bar, and co-working space.",
    indoor_courts: false,
    outdoor_courts: true,
    panoramic_glass: true,
    led_lighting: true,
    pro_shop: true,
    equipment_rental: true,
    coaching: true,
    tournaments: true,
    leagues: true,
    open_play: true,
    locker_rooms: true,
    parking: true,
    food_beverage: true,
    wheelchair_accessible: true,
    kids_programs: false,
    price_per_hour_cents: 4000,
    price_peak_cents: 6000,
    membership_available: true,
    avg_rating: 4.6,
    review_count: 28,
    is_featured: true,
  },
  {
    ...facilityDefaults,
    id: "demo-5",
    slug: "padel-haus-atlanta",
    name: "Padel Haus Atlanta",
    address: "950 W Marietta St NW, Suite A125",
    city: "Atlanta",
    city_slug: "atlanta",
    state: "Georgia",
    state_slug: "georgia",
    state_abbr: "GA",
    zip_code: "30318",
    latitude: 33.7729,
    longitude: -84.4124,
    phone: "(678) 919-2312",
    website: "https://www.padel.haus/atlanta",
    total_courts: 6,
    indoor_court_count: 6,
    outdoor_court_count: 0,
    surface_type: "artificial turf",
    description: "Atlanta's first indoor padel club at Westside Paper, featuring six courts including a center court for competition, with 40-foot ceilings.",
    indoor_courts: true,
    outdoor_courts: false,
    panoramic_glass: true,
    led_lighting: true,
    pro_shop: true,
    equipment_rental: true,
    coaching: true,
    tournaments: true,
    leagues: true,
    open_play: true,
    locker_rooms: true,
    parking: true,
    food_beverage: true,
    wheelchair_accessible: false,
    kids_programs: false,
    price_per_hour_cents: 5000,
    price_peak_cents: 8000,
    membership_available: true,
    avg_rating: 4.7,
    review_count: 31,
    is_featured: true,
  },
  {
    ...facilityDefaults,
    id: "demo-6",
    slug: "padel-haus-nashville",
    name: "Padel Haus Nashville",
    address: "2807 Grandview Ave",
    city: "Nashville",
    city_slug: "nashville",
    state: "Tennessee",
    state_slug: "tennessee",
    state_abbr: "TN",
    zip_code: "37211",
    latitude: 36.119,
    longitude: -86.769,
    phone: "(615) 813-2300",
    website: "https://www.padel.haus/nashville",
    total_courts: 8,
    indoor_court_count: 8,
    outdoor_court_count: 0,
    surface_type: "artificial turf",
    description: "The largest premium padel club in the U.S. with eight indoor courts, Gibson Lounge, Aescape massage table, and Juice Haus in Music City.",
    indoor_courts: true,
    outdoor_courts: false,
    panoramic_glass: true,
    led_lighting: true,
    pro_shop: true,
    equipment_rental: true,
    coaching: true,
    tournaments: true,
    leagues: true,
    open_play: true,
    locker_rooms: true,
    parking: true,
    food_beverage: true,
    wheelchair_accessible: false,
    kids_programs: false,
    price_per_hour_cents: 5000,
    price_peak_cents: 8000,
    membership_available: true,
    avg_rating: 4.8,
    review_count: 38,
    is_featured: true,
  },
  {
    ...facilityDefaults,
    id: "demo-7",
    slug: "padelhub-boston",
    name: "PADELHUB Boston",
    address: "653 Summer St",
    city: "Boston",
    city_slug: "boston",
    state: "Massachusetts",
    state_slug: "massachusetts",
    state_abbr: "MA",
    zip_code: "02210",
    latitude: 42.3411,
    longitude: -71.0438,
    phone: "(857) 413-6949",
    website: "https://www.padelhubusa.com",
    total_courts: 6,
    indoor_court_count: 6,
    outdoor_court_count: 0,
    surface_type: "artificial turf",
    description: "New England's largest padel facility in South Boston's Seaport with 6 indoor courts, 35+ ft ceilings, adidas pro-shop, lounge, and 45 free parking spots.",
    indoor_courts: true,
    outdoor_courts: false,
    panoramic_glass: true,
    led_lighting: true,
    pro_shop: true,
    equipment_rental: true,
    coaching: true,
    tournaments: true,
    leagues: true,
    open_play: true,
    locker_rooms: true,
    parking: true,
    food_beverage: true,
    wheelchair_accessible: true,
    kids_programs: false,
    price_per_hour_cents: 5000,
    price_peak_cents: 7500,
    membership_available: true,
    avg_rating: 4.5,
    review_count: 22,
    is_featured: true,
  },
  {
    ...facilityDefaults,
    id: "demo-8",
    slug: "padel-n9ne",
    name: "Padel N9NE",
    address: "9955 Barnes Canyon Rd",
    city: "San Diego",
    city_slug: "san-diego",
    state: "California",
    state_slug: "california",
    state_abbr: "CA",
    zip_code: "92121",
    latitude: 32.8856,
    longitude: -117.2099,
    phone: null,
    website: "https://www.padeln9ne.com",
    total_courts: 8,
    indoor_court_count: 0,
    outdoor_court_count: 8,
    surface_type: "artificial turf",
    description: "The first adidas padel flagship facility in the U.S. with 8 competition-level panoramic courts, gym and wellness facilities, plus five on-site restaurants.",
    indoor_courts: false,
    outdoor_courts: true,
    panoramic_glass: true,
    led_lighting: true,
    pro_shop: true,
    equipment_rental: true,
    coaching: true,
    tournaments: true,
    leagues: true,
    open_play: true,
    locker_rooms: true,
    parking: true,
    food_beverage: true,
    wheelchair_accessible: true,
    kids_programs: false,
    price_per_hour_cents: 5000,
    price_peak_cents: 8000,
    membership_available: true,
    avg_rating: 4.6,
    review_count: 25,
    is_featured: true,
  },
];

export const DEMO_STATES: State[] = [
  { id: "s-1", name: "Florida", slug: "florida", abbreviation: "FL", latitude: 27.6648, longitude: -81.5158, description: "Florida leads the US padel movement with the highest concentration of courts in the country.", meta_title: null, meta_description: null, facility_count: 17, created_at: now, updated_at: now },
  { id: "s-2", name: "California", slug: "california", abbreviation: "CA", latitude: 36.7783, longitude: -119.4179, description: "California's year-round sunshine makes it ideal for outdoor padel courts.", meta_title: null, meta_description: null, facility_count: 6, created_at: now, updated_at: now },
  { id: "s-3", name: "New York", slug: "new-york", abbreviation: "NY", latitude: 40.7128, longitude: -74.006, description: "New York's padel scene is booming with premium indoor facilities by Padel Haus.", meta_title: null, meta_description: null, facility_count: 4, created_at: now, updated_at: now },
  { id: "s-4", name: "Massachusetts", slug: "massachusetts", abbreviation: "MA", latitude: 42.4072, longitude: -71.3824, description: "Massachusetts has a growing padel community centered around Boston.", meta_title: null, meta_description: null, facility_count: 4, created_at: now, updated_at: now },
  { id: "s-5", name: "New Jersey", slug: "new-jersey", abbreviation: "NJ", latitude: 40.0583, longitude: -74.4057, description: "New Jersey offers multiple padel facilities across the state.", meta_title: null, meta_description: null, facility_count: 4, created_at: now, updated_at: now },
  { id: "s-6", name: "Georgia", slug: "georgia", abbreviation: "GA", latitude: 32.1656, longitude: -82.9001, description: "Georgia's padel scene is growing rapidly with Padel Haus Atlanta leading the way.", meta_title: null, meta_description: null, facility_count: 3, created_at: now, updated_at: now },
  { id: "s-7", name: "Texas", slug: "texas", abbreviation: "TX", latitude: 31.9686, longitude: -99.9018, description: "Texas is rapidly expanding its padel scene with Padel39 and other clubs.", meta_title: null, meta_description: null, facility_count: 2, created_at: now, updated_at: now },
  { id: "s-8", name: "Tennessee", slug: "tennessee", abbreviation: "TN", latitude: 35.5175, longitude: -86.5804, description: "Tennessee is home to the largest Padel Haus location in Nashville.", meta_title: null, meta_description: null, facility_count: 2, created_at: now, updated_at: now },
];

export const DEMO_CITIES: City[] = [
  { id: "c-1", state_id: "s-1", name: "North Miami", slug: "north-miami", state_slug: "florida", state_name: "Florida", state_abbr: "FL", latitude: 25.9092, longitude: -80.1652, population: 62468, description: "North Miami is home to Reserve Padel's flagship SoLe Mia location.", meta_title: null, meta_description: null, facility_count: 1, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
  { id: "c-2", state_id: "s-1", name: "Miami", slug: "miami", state_slug: "florida", state_name: "Florida", state_abbr: "FL", latitude: 25.7617, longitude: -80.1918, population: 442241, description: "Miami is the padel capital of the United States.", meta_title: null, meta_description: null, facility_count: 4, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
  { id: "c-3", state_id: "s-3", name: "Brooklyn", slug: "brooklyn", state_slug: "new-york", state_name: "New York", state_abbr: "NY", latitude: 40.6782, longitude: -73.9442, population: 2559903, description: "Brooklyn is the epicenter of NYC's padel scene with multiple Padel Haus locations.", meta_title: null, meta_description: null, facility_count: 4, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
  { id: "c-4", state_id: "s-2", name: "Los Angeles", slug: "los-angeles", state_slug: "california", state_name: "California", state_abbr: "CA", latitude: 34.0522, longitude: -118.2437, population: 3979576, description: "LA's padel community is growing rapidly with premium outdoor facilities.", meta_title: null, meta_description: null, facility_count: 2, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
  { id: "c-5", state_id: "s-7", name: "Austin", slug: "austin", state_slug: "texas", state_name: "Texas", state_abbr: "TX", latitude: 30.2672, longitude: -97.7431, population: 978908, description: "Austin's active culture embraces padel with Padel39's premium outdoor courts.", meta_title: null, meta_description: null, facility_count: 1, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
  { id: "c-6", state_id: "s-6", name: "Atlanta", slug: "atlanta", state_slug: "georgia", state_name: "Georgia", state_abbr: "GA", latitude: 33.749, longitude: -84.388, population: 498715, description: "Atlanta's padel scene centers around Padel Haus at Westside Paper.", meta_title: null, meta_description: null, facility_count: 2, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
  { id: "c-7", state_id: "s-8", name: "Nashville", slug: "nashville", state_slug: "tennessee", state_name: "Tennessee", state_abbr: "TN", latitude: 36.1627, longitude: -86.7816, population: 715884, description: "Nashville hosts the largest Padel Haus location in the United States.", meta_title: null, meta_description: null, facility_count: 2, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
  { id: "c-8", state_id: "s-4", name: "Boston", slug: "boston", state_slug: "massachusetts", state_name: "Massachusetts", state_abbr: "MA", latitude: 42.3601, longitude: -71.0589, population: 675647, description: "Boston's Seaport district is home to PADELHUB, New England's largest padel facility.", meta_title: null, meta_description: null, facility_count: 3, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
  { id: "c-9", state_id: "s-2", name: "San Diego", slug: "san-diego", state_slug: "california", state_name: "California", state_abbr: "CA", latitude: 32.7157, longitude: -117.1611, population: 1386932, description: "San Diego features the first adidas padel flagship at Padel N9NE.", meta_title: null, meta_description: null, facility_count: 3, guide_intro: null, guide_body: null, guide_generated_at: null, created_at: now, updated_at: now },
];

export const DEMO_FACILITY_COUNT = 54;
